Filters
Nyar1othotep/fwt-art-gallery pull request #3
Opened 2023-11-28 12:09 UTC by Nyar1othotep

2023-11-28 13:36 UTC, lightsout1993 requested changes

2023-11-28 13:36 UTC, lightsout1993 commented on src/shared/lib/useOutsideClick.ts
> +      handler();
инвертируй условие

2023-11-28 13:36 UTC, lightsout1993 commented on src/shared/styles/base.scss
> +._ibg {
давай название более понятное

2023-11-28 13:36 UTC, lightsout1993 commented on src/shared/ui/Image/Image.tsx
> +          />
заглушку вынеси и разрули здесь это

2023-11-28 13:36 UTC, lightsout1993 commented on src/shared/ui/Image/Image.tsx
> +      {isError && (
onLoad

2023-11-28 13:36 UTC, lightsout1993 commented on src/shared/ui/Link/Link.tsx
> +  onClick,
используй spread

2023-11-28 13:36 UTC, lightsout1993 commented on src/shared/ui/Search/Search.tsx
> +      onSearchChange(e.target.value);
onSearchChange?.(e.target.value);

2023-11-28 13:36 UTC, lightsout1993 commented on src/widgets/artists/lib/useArtistsFetchData.ts
> +  const { data = {}, isLoading } = useGetArtistsQuery(
const { perPage = 0,  pageNumber = 0 } = filters;

2023-11-28 13:36 UTC, lightsout1993 commented on src/widgets/artists/lib/useArtistsFetchData.ts
> +        perPage: +filters.perPage * +filters.pageNumber,
Number

2023-11-28 13:36 UTC, lightsout1993 commented on src/widgets/artists/ui/ArtistInfo/ArtistInfo.tsx
> +              ? artist.genres.map(({ _id, name }) => (
artist.genres?.map

2023-11-28 13:36 UTC, lightsout1993 commented on src/widgets/artworks/ui/ArtworksLayout/ArtworksLayout.tsx
> +      {/* // TODO: Добавить сюда скелетон */}
убери

2023-11-28 13:36 UTC, lightsout1993 commented on src/widgets/artworks/ui/ArtworksSlider/ArtworksSlider.tsx
> +  return (
попробуй разгрузить jsx

2023-11-30 06:40 UTC, Nyar1othotep commented on src/shared/ui/Image/Image.tsx
> +          />
Заглушку вынес, но оставил такой подход:
`if (!image) return <ErrorImage title="No image uploaded" />`

2023-11-30 06:45 UTC, Nyar1othotep commented on src/features/filters/ui/FiltersLayout/FiltersLayout.tsx
> +            </Button>
Кнопки как часть Sidebar в FiltersLayout. Я считаю, что вынося их отдельно,  станет тяжело читать код. 

`

       <Sidebar theme={theme} isShow={isShow} onClose={handleClose}>
        <div
          className={cx("filters-layout__sidebar-content", "sidebar-content")}
        >
        ...
           <div className={cx("sidebar-content__controls")}>
            <Button theme={theme} variant="text" onClick={handleResult}>
              Show the result
            </Button>
            <Button theme={theme} variant="text" onClick={handleClear}>
              Clear
            </Button>
          </div>
        </div>
      </Sidebar>`

2024-07-05 10:33 UTC, merged